services:
  docling-streamlit:
    image: docling-streamlit:latest
    build: .
    container_name: docling-streamlit
    hostname: docling-streamlit
    ipc: host
    restart: always
    volumes:
      - ./cache:/root/.cache
      - ./streamlit_app.py:/app/streamlit_app.py
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8501:8501"
    #user: "1000:1000"
    tmpfs:
      - /tmp
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              #count: all
              device_ids: ["1"]
